"""initial_schema

Revision ID: 2a3b25eb8647
Revises: 
Create Date: 2026-04-28 20:29:08.423993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a3b25eb8647'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('concession_slug', sa.String(length=200), nullable=False),
    sa.Column('qualification_level', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_concession_slug'), 'agents', ['concession_slug'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sub_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=50), server_default='FR', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('surface_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mandate_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_prestige', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_advisor_id'), 'properties', ['advisor_id'], unique=False)
    op.create_index('ix_properties_city', 'properties', ['city'], unique=False)
    op.create_index('ix_properties_mandate_price', 'properties', ['mandate_price'], unique=False)
    op.create_index('ix_properties_status', 'properties', ['status'], unique=False)
    op.create_index('ix_properties_type', 'properties', ['type'], unique=False)
    op.create_index(op.f('ix_properties_uid'), 'properties', ['uid'], unique=True)
    op.create_table('descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'locale', name='uq_description_property_locale')
    )
    op.create_index('ix_descriptions_property_id', 'descriptions', ['property_id'], unique=False)
    op.create_table('mandates',
    sa.Column('mandate_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exclusivity_terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('property_city', sa.String(length=100), nullable=True),
    sa.Column('property_surface', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('property_designation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('mandate_id'),
    sa.UniqueConstraint('order_number', name='uq_mandate_order_number')
    )
    op.create_index('ix_mandates_agent_id', 'mandates', ['agent_id'], unique=False)
    op.create_index('ix_mandates_property_id', 'mandates', ['property_id'], unique=False)
    op.create_index('ix_mandates_validated_at', 'mandates', ['validated_at'], unique=False)
    op.create_table('property_listings',
    sa.Column('property_listing_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('first_publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broadcast_mode', sa.String(length=50), nullable=True),
    sa.Column('geography', sa.Text(), nullable=True),
    sa.Column('show_price', sa.Boolean(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_listing_id')
    )
    op.create_index('ix_property_listings_property_id', 'property_listings', ['property_id'], unique=False)
    op.create_table('mandate_rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandate_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('rental_type', sa.String(length=50), nullable=True),
    sa.Column('lease_duration', sa.Integer(), nullable=True),
    sa.Column('availability_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rent_net', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rent_charges', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('security_deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_frequency', sa.String(length=50), nullable=True),
    sa.Column('effectivepricing_net', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effectivepricing_charges', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effectivepricing_changedat', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.mandate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandate_id', name='uq_mandate_rental_mandate_id')
    )
    op.create_index('ix_mandate_rentals_availability_at', 'mandate_rentals', ['availability_at'], unique=False)
    op.create_table('mandate_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandate_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('pricing_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pricing_netprice', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effectivepricing_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effectivepricing_netprice', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effectivepricing_changedat', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.mandate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandate_id', name='uq_mandate_sale_mandate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mandate_sales')
    op.drop_index('ix_mandate_rentals_availability_at', table_name='mandate_rentals')
    op.drop_table('mandate_rentals')
    op.drop_index('ix_property_listings_property_id', table_name='property_listings')
    op.drop_table('property_listings')
    op.drop_index('ix_mandates_validated_at', table_name='mandates')
    op.drop_index('ix_mandates_property_id', table_name='mandates')
    op.drop_index('ix_mandates_agent_id', table_name='mandates')
    op.drop_table('mandates')
    op.drop_index('ix_descriptions_property_id', table_name='descriptions')
    op.drop_table('descriptions')
    op.drop_index(op.f('ix_properties_uid'), table_name='properties')
    op.drop_index('ix_properties_type', table_name='properties')
    op.drop_index('ix_properties_status', table_name='properties')
    op.drop_index('ix_properties_mandate_price', table_name='properties')
    op.drop_index('ix_properties_city', table_name='properties')
    op.drop_index(op.f('ix_properties_advisor_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_agents_concession_slug'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
